# MySQL datasource
# datasource:
#    url: jdbc:mysql://localhost:3306/exchange_arbitr?useSSL=false
#  jpa:
#    properties.hibernate:
#      dialect: org.hibernate.dialect.MySQL5Dialect
#      current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
#    hibernate.ddl-auto: update
logging.file: ../logs/exchange-arbitr.log
spring:
  jpa:
    # Let Spring autodetect the different SQL Dialects of each datasource
    database: default
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    generate-ddl: true
    # used for jsf el session resolve problem
    properties.hibernate:
      current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
#      show_sql: true
#      use_sql_comments: true
#      format_sql: true
#    properties.hibernate:
#      current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

# In-Memory H2 database for monitoring and fast calculating of real-time forks.
#  datasource:
#    url: jdbc:h2:mem:shorttime2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
#    username: fe
#    password: noMONEY0607noHoney
#    driverClassName: org.h2.Driver
#    tomcat.max-active: 300
#    tomcat.max-idle: 30
  datasource:
    url: jdbc:mysql://localhost:3306/exchange_arbitr_fast
    username: fedr
    password: 351
    driver-class-name: com.mysql.jdbc.Driver
    tomcat.max-active: 150
    tomcat.max-idle: 15
  profiles.active: @activatedProperties@
# H2 In-Memory Database "bar" (used in tests instead of a real PostgreSQL DB)
longtime.datasource:
  url: jdbc:mysql://localhost:3306/exchange_arbitr
  username: fedr
  password: 351
  driver-class-name: com.mysql.jdbc.Driver
  tomcat.max-active: 100
  tomcat.max-idle: 15
###
#   H2 Settings
###
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
proxy.list: 185.128.215.224:8000,193.93.60.95:8000,193.93.60.236:8000,194.242.127.221:8000,193.93.60.25:8000,194.242.127.67:8000,91.234.11.57:8000,194.242.127.36:8000
---
spring:
  profiles: dev
  datasource:
    username: fedr
    password: 351
#show sql statement
#logging.level.org.hibernate.SQL: debug
#show sql values
#logging.level.org.hibernate.type.descriptor.sql: trace
---
spring:
  profiles: hosting
  jpa:
    hibernate.ddl-auto: update
longtime.datasource.datasource:
  username: exchange_fedr
  password: profit3001PUSHKA
---
