logging.file: ../logs/mylog.log
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exchange_arbitr?useSSL=false
  jpa:
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    hibernate.ddl-auto: update
  profiles.active: @activatedProperties@
---
spring:
  profiles: dev
  jpa:
    hibernate.show-sql: true
  datasource:
    username: fedr
    password: 351
---
spring:
  profiles: hosting
  datasource:
    username: exchange_fedr
    password: profit3001PUSHKA
---
