# one datasource config MySQL datasource
# datasource:
#    url: jdbc:mysql://localhost:3306/exchange_arbitr?useSSL=false
#  jpa:
#    properties.hibernate:
#      dialect: org.hibernate.dialect.MySQL5Dialect
#      current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
#    hibernate.ddl-auto: update
logging.file: ../logs/exchange-arbitr.log
spring:
  jpa:
    # Let Spring autodetect the different SQL Dialects of each datasource
    database: default
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    generate-ddl: true
    # used for jsf el session resolve problem
    properties.hibernate:
#      dialect: org.hibernate.dialect.Oracle10gDialect
      current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
#      show_sql: true
#      use_sql_comments: true
#      format_sql: true
#    properties.hibernate:
#      current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

# In-Memory H2 database for monitoring and fast calculating of real-time forks.
  datasource:
    url: jdbc:h2:mem:shorttime1004;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
    username: fe
    password: noMONEY0607noHoney
    driverClassName: org.h2.Driver
    tomcat.max-active: 300
    tomcat.max-idle: 30
  profiles.active: @activatedProperties@
# POSTGRE database for TEST monitoring and fast calculating of real-time forks.
#  datasource:
#    url: jdbc:postgresql://localhost:5432/shorttime
#    username: postgres
#    password: 351
#    driver-class-name: org.postgresql.Driver
#    testWhileIdle: true
#    spring.datasource.validationQuery: SELECT 1
#    tomcat:
#      max-active: 150
#      max-idle: 15
#      validation-query: SELECT 1
#      test-while-idle: true

# Oracle database for TEST monitoring and fast calculating of real-time forks.
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521:XE
#    username: exchange_arbitr_fast
#    password: 351
#    driver-class-name: oracle.jdbc.OracleDriver
#    testWhileIdle: true
#    spring.datasource.validationQuery: SELECT 1
#    tomcat:
#      max-active: 150
#      max-idle: 15
#      validation-query: SELECT 1
#      test-while-idle: true

# MySql database for TEST monitoring and fast calculating of real-time forks.
#  datasource:
#    url: jdbc:mysql://localhost:3306/exchange_arbitr_fast
#    username: fedr
#    password: 351
#    driver-class-name: com.mysql.jdbc.Driver
#    tomcat.max-active: 150
#    tomcat.max-idle: 15
# Long time Database POSTGRE
longtime.datasource:
  url: jdbc:postgresql://localhost:5432/longtime1004
  username: postgres
  password: 351
  driver-class-name: org.postgresql.Driver
  testWhileIdle: true
  validationQuery: SELECT 1
  schema: public
  tomcat:
    max-active: 150
    max-idle: 15
    validation-query: SELECT 1
    test-while-idle: true
## Long time Database MySql
#longtime.datasource:
#  url: jdbc:mysql://localhost:3306/exchange_arbitr
#  username: fedr
#  password: 351
#  driver-class-name: com.mysql.jdbc.Driver
#  tomcat.max-active: 100
#  tomcat.max-idle: 15
# Long time Database Oracle
#longtime.datasource:
#
#  url: jdbc:oracle:thin:@localhost:1521:XE
#  username: exchange_arbitr_long
#  password: 351
#  driver-class-name: oracle.jdbc.OracleDriver
#  testWhileIdle: true
#  validationQuery: SELECT 1
#  tomcat:
#    max-active: 150
#    max-idle: 15
#    validation-query: SELECT 1
#    test-while-idle: true
###
#   H2 Settings
###
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
proxy.list: 91.234.11.6:8000,91.241.47.65:8000,194.242.127.61:8000,193.93.60.157:8000,194.242.127.204:8000,194.242.127.139:8000,91.241.47.176:8000,193.93.60.149:8000,194.242.127.166:8000,91.234.11.99:8000,91.234.11.191:8000,91.234.11.64:8000,194.242.127.221:8000,194.242.127.250:8000,91.241.47.110:8000,91.241.47.153:8000,194.242.127.99:8000,91.241.47.27:8000,185.147.193.108:8000,185.147.194.188:8000
---
spring:
  profiles: dev
#show sql statement
#logging.level.org.hibernate.SQL: debug
#show sql values
#logging.level.org.hibernate.type.descriptor.sql: trace
---
spring:
  profiles: hosting
  jpa:
    hibernate.ddl-auto: update
longtime.datasource:
  url: jdbc:postgresql://104.155.111.23:5432/longtime1004
  username: postgres
  password: fktr7429YOR
  driver-class-name: org.postgresql.Driver
  testWhileIdle: true
  validationQuery: SELECT 1
  schema: public
  tomcat:
    max-active: 150
    max-idle: 15
    validation-query: SELECT 1
    test-while-idle: true
---
