# MySQL datasource
# datasource:
#    url: jdbc:mysql://localhost:3306/exchange_arbitr?useSSL=false
#  jpa:
#    properties.hibernate:
#      dialect: org.hibernate.dialect.MySQL5Dialect
#      current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
#    hibernate.ddl-auto: update
logging.file: ../logs/exchange-arbitr.log
spring:
  jpa:
    # Let Spring autodetect the different SQL Dialects of each datasource
    database: default
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    generate-ddl: true
    # used for jsf el session resolve problem
    properties.hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
#    properties.hibernate:
#      current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
# In-Memory H2 database for monitoring and fast calculating of real-time forks.
  datasource:
    url: jdbc:h2:mem:shorttime2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: fe
    password:
    driverClassName: org.h2.Driver
  profiles.active: @activatedProperties@
# H2 In-Memory Database "bar" (used in tests instead of a real PostgreSQL DB)
longtime.datasource:
  url: jdbc:mysql://localhost:3306/exchange_arbitr
  username: fedr
  password: 351
  driver-class-name: com.mysql.jdbc.Driver
###
#   H2 Settings
###
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
---
spring:
  profiles: dev
  datasource:
    username: fedr
    password: 351
#show sql statement
#logging.level.org.hibernate.SQL: debug
#show sql values
#logging.level.org.hibernate.type.descriptor.sql: trace
---
spring:
  profiles: hosting
  datasource:
    username: exchange_fedr
    password: profit3001PUSHKA
  jpa:
    hibernate.ddl-auto: update
---
